// GENERATED by tools/api-snapshot.mjs — do not edit by hand.
//
// The `types@<5.9` gate of design/08 §2.2, first in every condition object of every subpath in
// package.json. A consumer on TypeScript < 5.9 resolves `@pg-prime/kit` to THIS file instead of the
// real declarations, so every name still exists and every USE of one lands the message in the
// error text. Verified against TypeScript 5.8.3 by tools/pack-smoke.mjs on every run:
//
//   consumer.ts(12,15): error TS2349: This expression is not callable.
//     Type '{ ERROR: "@pg-prime/kit requires TypeScript >= 5.9 — see https://pg-prime.dev/ts"; }' has no call signatures.
//
// Naming the key `ERROR` rather than a `__dunder__` is §2.2's own refinement over Kysely's
// version: it reads first in a truncated hover.
//
// ## `Unsupported<M = …> = M` is an identity alias ON PURPOSE — do not "simplify" it
//
// Written the obvious way, `type Unsupported = { ERROR: '…' }`, TypeScript prints the ALIAS NAME
// in the diagnostic — "Type 'Unsupported' has no call signatures" — and the message never
// reaches the user, which defeats the entire file. A generic alias whose body is just its own
// parameter has no alias symbol to print, so the checker falls back to the structural form and
// the sentence appears. Measured, both shapes, on 5.9.3 and 5.8.3.
//
// The lists are the root entry's value and type exports, taken from tools/api-snapshot/*.json.
// `node tools/api-snapshot.mjs --check` fails if this file and that golden disagree, which is
// what stops the stub from silently rotting into "this package has no exported member 'x'".
// The type parameters are optional and are only as many as the real declaration has, so that a
// generic use resolves to the brand instead of erroring with "is not generic".

type Unsupported<Message = { ERROR: '@pg-prime/kit requires TypeScript >= 5.9 — see https://pg-prime.dev/ts' }> = Message

export declare const CATALOG_PROVENANCE: Unsupported
export declare const DUMP_SAMPLE_CAP: Unsupported
export declare const DUMP_TIMEOUT_MS: Unsupported
export declare const ENGINE: Unsupported
export declare const InvalidIdentifierError: Unsupported
export declare const InvalidMigrationIdError: Unsupported
export declare const MAX_IDENT_BYTES: Unsupported
export declare const MIGRATION_NAME: Unsupported
export declare const PHASE: Unsupported
export declare const ProofRequiredError: Unsupported
export declare const SHADOW_PREFIX: Unsupported
export declare const SQLSTATE_OBJECT_IN_USE: Unsupported
export declare const SchemaIR: Unsupported
export declare const SpawnFailure: Unsupported
export declare const UnacknowledgedHazardError: Unsupported
export declare const UnsafeCloneNameError: Unsupported
export declare const UnsafeDatabaseNameError: Unsupported
export declare const UnsafePlanPathError: Unsupported
export declare const WriteRefusedError: Unsupported
export declare const acquireSessionLock: Unsupported
export declare const advisoryLockKey: Unsupported
export declare const applyRenameHints: Unsupported
export declare const applySegments: Unsupported
export declare const buildPlan: Unsupported
export declare const buildStatements: Unsupported
export declare const canonicalize: Unsupported
export declare const canonicalizeSql: Unsupported
export declare const columnClause: Unsupported
export declare const compareDumps: Unsupported
export declare const connectionString: Unsupported
export declare const contentHash: Unsupported
export declare const createDatabase: Unsupported
export declare const definitionsAgreeUnderRename: Unsupported
export declare const detectTransactionPooler: Unsupported
export declare const diffIR: Unsupported
export declare const dollarTagAt: Unsupported
export declare const dropDatabase: Unsupported
export declare const dumpSchema: Unsupported
export declare const encodeId: Unsupported
export declare const evaluatedEnumLabels: Unsupported
export declare const extractCatalog: Unsupported
export declare const generate: Unsupported
export declare const hasLoneSurrogate: Unsupported
export declare const hasNul: Unsupported
export declare const hazardSeverity: Unsupported
export declare const idName: Unsupported
export declare const isEmptyDiff: Unsupported
export declare const isObjectInUse: Unsupported
export declare const isShadowDatabase: Unsupported
export declare const isValidIdent: Unsupported
export declare const labelsOf: Unsupported
export declare const lexSql: Unsupported
export declare const migrationId: Unsupported
export declare const normalizeDump: Unsupported
export declare const orderStatements: Unsupported
export declare const parentOf: Unsupported
export declare const parseId: Unsupported
export declare const parseLauncherEnv: Unsupported
export declare const planSql: Unsupported
export declare const proveOnShadowClone: Unsupported
export declare const quoteIdent: Unsupported
export declare const quoteLiteral: Unsupported
export declare const quoteQualified: Unsupported
export declare const releaseSessionLock: Unsupported
export declare const renderSql: Unsupported
export declare const resolvePgDump: Unsupported
export declare const runSqlScript: Unsupported
export declare const schemaPattern: Unsupported
export declare const sha256: Unsupported
export declare const splitStatements: Unsupported
export declare const terminateConnections: Unsupported
export declare const tokenizeDefinition: Unsupported
export declare const utf8ByteLength: Unsupported
export declare const withClient: Unsupported
export declare const withDatabase: Unsupported
export declare const writePlan: Unsupported

export type AcknowledgeInput = Unsupported
export type Acknowledgement = Unsupported
export type AnyPayload = Unsupported
export type ApplyReport = Unsupported
export type BuildResult = Unsupported
export type CatalogClient = Unsupported
export type ColumnPayload = Unsupported
export type ConnInfo = Unsupported
export type ConstraintPayload = Unsupported
export type Delta = Unsupported
export type DependencyEdge = Unsupported
export type Diagnostic = Unsupported
export type DiffOptions = Unsupported
export type DiffResult = Unsupported
export type DumpComparison = Unsupported
export type DumpOracleMode = Unsupported
export type DumpOracleVerdict = Unsupported
export type DumpRequest = Unsupported
export type EdgeKind = Unsupported
export type EnumLabelPayload = Unsupported
export type ExtractResult = Unsupported
export type Fact = Unsupported
export type FactKind = Unsupported
export type GenerateInput = Unsupported
export type GenerateResult = Unsupported
export type Hash = Unsupported
export type IdentifierProblem = Unsupported
export type IndexPayload = Unsupported
export type InvalidIdentifierError = Unsupported
export type InvalidMigrationIdError = Unsupported
export type LockClass = Unsupported
export type OrderResult = Unsupported
export type Origin = Unsupported
export type Ownership = Unsupported
export type Payload = Unsupported
export type PgDumpLauncher = Unsupported
export type Plan = Unsupported
export type PlanHazard = Unsupported
export type PlanStatement = Unsupported
export type Proof = Unsupported
export type ProofRequiredError = Unsupported
export type ProofResult = Unsupported
export type ProveInput = Unsupported
export type Provenance = Unsupported
export type RenameHint = Unsupported
export type RenameRecord = Unsupported
export type ResolvedPgDump = Unsupported
export type SchemaIR = Unsupported
export type SchemaPayload = Unsupported
export type Segment = Unsupported
export type SequencePayload = Unsupported
export type ShadowProvisioning = Unsupported
export type SpawnFailure = Unsupported
export type SqlSegment = Unsupported
export type StableId = Unsupported
export type Statement = Unsupported
export type TablePayload = Unsupported
export type Transactionality = Unsupported
export type TypePayload = Unsupported
export type UnacknowledgedHazardError = Unsupported
export type UnsafeCloneNameError = Unsupported
export type UnsafeDatabaseNameError = Unsupported
export type UnsafePlanPathError = Unsupported
export type WriteRefusedError = Unsupported
