import { describe, expect, it } from 'vitest'
import { expectTypeOf } from 'expect-type'
import type {
  DateString,
  Insert,
  Insertable,
  Refs,
  Row,
  Selectable,
  Update,
  Updateable,
} from '../../src/schema/index.js'
import { META, OUT, pgTable } from '../../src/schema/index.js'
import { users, type UserId, type UserPrefs } from './fixture.js'

type RequiredKeys<T> = { [K in keyof T]-?: {} extends Pick<T, K> ? never : K }[keyof T]
type OptionalKeys<T> = { [K in keyof T]-?: {} extends Pick<T, K> ? K : never }[keyof T]

describe('SelectRow ($inferSelect)', () => {
  it('is one indexed access per column, with nullability already absorbed into `t`', () => {
    expectTypeOf<Selectable<typeof users>>().toEqualTypeOf<{
      id: UserId
      email: string
      displayName: string | null
      age: number | null
      views: bigint
      active: boolean
      prefs: UserPrefs
      tags: string[]
      role: 'owner' | 'admin' | 'member'
      birthday: DateString | null
      balance: string
      createdAt: Date
      updatedAt: Date
      seq: bigint
      slug: string
    }>()
  })

  it('columns are NOT NULL by default; only `.nullable()` widens', () => {
    expectTypeOf<Selectable<typeof users>['email']>().toEqualTypeOf<string>()
    expectTypeOf<Selectable<typeof users>['displayName']>().toEqualTypeOf<string | null>()
  })

  it('decode defaults: int8 → bigint, timestamptz → Date, numeric → string, date → branded string', () => {
    expectTypeOf<Selectable<typeof users>['views']>().toEqualTypeOf<bigint>()
    expectTypeOf<Selectable<typeof users>['createdAt']>().toEqualTypeOf<Date>()
    expectTypeOf<Selectable<typeof users>['balance']>().toEqualTypeOf<string>()
    // a `date` is a branded 'YYYY-MM-DD' string — never a Date, and a bare
    // string is not assignable to it
    expectTypeOf<Selectable<typeof users>['birthday']>().not.toEqualTypeOf<Date | null>()
    expectTypeOf<string>().not.toExtend<DateString>()
    expectTypeOf<DateString>().toExtend<string>()
  })

  it('$type narrows: jsonb → an object type, uuid → a branded scalar', () => {
    expectTypeOf<Selectable<typeof users>['prefs']>().toEqualTypeOf<UserPrefs>()
    expectTypeOf<Selectable<typeof users>['id']>().toEqualTypeOf<UserId>()
  })

  it('arrays and enums', () => {
    expectTypeOf<Selectable<typeof users>['tags']>().toEqualTypeOf<string[]>()
    expectTypeOf<Selectable<typeof users>['role']>().toEqualTypeOf<'owner' | 'admin' | 'member'>()
  })
})

describe('InsertRow ($inferInsert)', () => {
  it('only NOT NULL columns without any default are required', () => {
    expectTypeOf<RequiredKeys<Insertable<typeof users>>>().toEqualTypeOf<'email'>()
  })

  it('nullable | DDL default | $default | identity-by-default are all optional', () => {
    expectTypeOf<OptionalKeys<Insertable<typeof users>>>().toEqualTypeOf<
      | 'id'
      | 'displayName'
      | 'age'
      | 'views'
      | 'active'
      | 'prefs'
      | 'tags'
      | 'role'
      | 'birthday'
      | 'balance'
      | 'createdAt'
      | 'updatedAt'
      | 'slug'
    >()
  })

  it('GENERATED ALWAYS columns are absent entirely', () => {
    expectTypeOf<Insertable<typeof users>>().not.toHaveProperty('seq')
  })

  it('a defaulted column is still non-null on read and on write', () => {
    expectTypeOf<Insertable<typeof users>['views']>().toEqualTypeOf<bigint | undefined>()
  })
})

describe('UpdateRow ($inferUpdate)', () => {
  it('everything writable, all optional, GENERATED ALWAYS still absent', () => {
    expectTypeOf<RequiredKeys<Updateable<typeof users>>>().toEqualTypeOf<never>()
    expectTypeOf<Updateable<typeof users>>().not.toHaveProperty('seq')
    expectTypeOf<Updateable<typeof users>['email']>().toEqualTypeOf<string | undefined>()
  })
})

describe('the two spellings of the row shapes', () => {
  it('design/05 D3 `Row`/`Insert`/`Update` and design/04 `Selectable`/`Insertable`/`Updateable` are the same types', () => {
    expectTypeOf<Row<typeof users>>().toEqualTypeOf<Selectable<typeof users>>()
    expectTypeOf<Insert<typeof users>>().toEqualTypeOf<Insertable<typeof users>>()
    expectTypeOf<Update<typeof users>>().toEqualTypeOf<Updateable<typeof users>>()
  })
})

describe('identity columns', () => {
  const seqs = pgTable('seqs', (t) => ({
    // GENERATED ALWAYS AS IDENTITY — never writable
    always: t.integer().generatedAlways(),
    // GENERATED BY DEFAULT AS IDENTITY — optional on insert, still updatable
    byDefault: t.integer().generatedByDefault(),
    small: t.smallint(),
  }))

  it('generatedAlways is absent from insert and update; generatedByDefault is optional in both', () => {
    expectTypeOf<Insertable<typeof seqs>>().not.toHaveProperty('always')
    expectTypeOf<Updateable<typeof seqs>>().not.toHaveProperty('always')
    expectTypeOf<Insertable<typeof seqs>['byDefault']>().toEqualTypeOf<number | undefined>()
    expectTypeOf<Updateable<typeof seqs>['byDefault']>().toEqualTypeOf<number | undefined>()
    // both are present, non-null, on read
    expectTypeOf<Selectable<typeof seqs>>().toEqualTypeOf<{
      always: number
      byDefault: number
      small: number
    }>()
  })

  it('records the identity kind in the DDL IR', () => {
    expect(seqs.$.column('always')!.ddl.identity).toBe('always')
    expect(seqs.$.column('byDefault')!.ddl.identity).toBe('byDefault')
    expect(seqs.$.column('small')!.ddl.pgType).toBe('int2')
  })
})

describe('column refs (the pre-computed [REFS] slot)', () => {
  it('carry the source alias, the key and the column meta', () => {
    type R = Refs<typeof users>
    expectTypeOf<R['email'][typeof OUT]>().toEqualTypeOf<string>()
    expectTypeOf<R['email'][typeof META]>().toEqualTypeOf<{
      t: string
      pg: 'text'
      opt: false
      ro: false
      pk: false
    }>()
    expectTypeOf<R['tags'][typeof META]['pg']>().toEqualTypeOf<'text[]'>()
    expectTypeOf<R['views'][typeof META]['pg']>().toEqualTypeOf<'int8'>()
    expectTypeOf<R['role'][typeof META]['pg']>().toEqualTypeOf<'member_role'>()
    // `pk` is declared per column and is what design/03 §2.3's GROUP BY guard reads.
    expectTypeOf<R['id'][typeof META]['pk']>().toEqualTypeOf<true>()
    expectTypeOf<R['email'][typeof META]['pk']>().toEqualTypeOf<false>()
  })
})

describe('the `$` law: a `$`-prefixed method never affects DDL', () => {
  const col = (k: string) => users.$.column(k)!

  it('.default() writes the DDL default', () => {
    expect(col('views').ddl.default).toEqual({ kind: 'value', value: 0n })
    expect(col('id').ddl.default).toEqual({ kind: 'expr', expr: 'gen_random_uuid()' })
  })

  it('.$default() does NOT write the DDL default', () => {
    expect(col('slug').ddl.default).toBeUndefined()
    expect(typeof col('slug').ts.defaultFn).toBe('function')
    expect(col('slug').ts.defaultFn!()).toBe('anonymous')
  })

  it('.$onUpdate() does NOT emit a trigger or a DDL default', () => {
    expect(col('updatedAt').ts.onUpdateFn).toBeTypeOf('function')
    expect(col('updatedAt').ddl.default).toEqual({ kind: 'expr', expr: 'now()' })
  })

  it('.$type() leaves the DDL identical', () => {
    expect(col('prefs').ddl.pgType).toBe('jsonb')
    expect(col('prefs').ts.narrowed).toBe(true)
    expect(col('id').ddl.pgType).toBe('uuid')
  })

  it('NOT NULL by default; .nullable() opts out', () => {
    expect(col('email').ddl.notNull).toBe(true)
    expect(col('displayName').ddl.notNull).toBe(false)
  })

  it('carries enum/array/identity facts the migration IR needs', () => {
    expect(col('role').ddl.enumValues).toEqual(['owner', 'admin', 'member'])
    expect(col('tags').ddl.arrayDim).toBe(1)
    expect(col('tags').ddl.pgType).toBe('text[]')
    expect(col('seq').ddl.identity).toBe('always')
  })
})

describe('table runtime', () => {
  it('applies the snake_case casing strategy and evaluates extras against refs', () => {
    expect(users.$.name).toBe('users')
    expect(users.$.columns.find((c) => c.key === 'displayName')?.dbName).toBe('display_name')
    expect(users.$.extras).toEqual([
      { node: 'index', name: 'users_email_idx', unique: true, columns: ['email'] },
      { node: 'comment', text: 'Application user accounts.' },
    ])
  })
})
