/**
 * The codec seam (design/09 WS2): schema `ColumnRuntime` → compiler `ColumnMeta` → `src/codec`.
 *
 * This is the one place a `pgTable(...)` column's declared PostgreSQL type is turned into a real
 * `Codec`. Everything downstream — the compiler's `::type` casts, `json_build_object`'s per-column
 * cast, the positional decoder, `assertShape`'s OID check — reads the codec off the `ColumnMeta`
 * this module produces, so there is exactly one lookup per (table, registry) and none per query.
 *
 * Three rules, each of which exists because of a specific failure:
 *
 *  1. **Fail at `metaOf` time, never at query time.** A column whose type has no codec cannot be
 *     encoded or decoded. Discovering that while a statement is in flight means the query already
 *     reached the server; `NoCodecError` fires here instead, once, naming the column.
 *
 *  2. **Identifiers are pre-quoted here and nowhere else** (03 §7). The compiler must never quote
 *     a schema identifier on the hot path, so `tableMeta`/`columnMeta` do it at seam-build time.
 *
 *  3. **The cache is keyed by (registry, table) and invalidated by `registry.generation`.** A
 *     `TableMeta` built before `resolveDynamic` carries an enum codec whose `oid` is `undefined`;
 *     after resolution the registry holds one with the real OID. Without the generation check the
 *     stale meta would survive and `assertShape` would compare a live `dataTypeID` against nothing.
 */

import { arrayCodecOf, defaultRegistry } from '../codec/index.js'
import type { AnyCodec, CodecRegistry } from '../codec/index.js'
import type { ColumnMeta, TableMeta } from '../compile/ast.js'
import { columnMeta, tableMeta } from '../compile/nodes.js'
import type { ColumnDdl } from '../schema/column.js'
import type { TableRuntime } from '../schema/table.js'
import { NoCodecError } from '../sql/errors.js'
import { quoteIdentPart } from '../sql/ident.js'

/**
 * Anything carrying a `TableRuntime`: a `Table` from `pgTable(...)`, or a `Handle` from
 * `defineSchema(...)`. The seam reads `$` and nothing else, and `db.from()` is handed handles —
 * so constraining to `AnyTable` here would force a cast at every builder call site (R12).
 */
export type TableLike = { readonly $: TableRuntime }

/**
 * Everything the compile layer needs about one table. `columns` is in declaration order, which is
 * the order `insert into t (...) values (...)` and a `select *` projection use.
 */
export interface TableCodecMeta {
  readonly table: TableMeta
  /** Declaration order. */
  readonly columns: readonly ColumnMeta[]
  /** Declaration order, TS keys — parallel to `columns`. */
  readonly keys: readonly string[]
  /**
   * `keys` minus every column the database computes, in declaration order — the runtime half of
   * the rule the type level already enforces, where `ro: true` removes a column from
   * `InsertPatch`. COPY reads it because it builds its column list from the SCHEMA rather than
   * from the caller's row keys, and had no other way to know (design/13 §5, E's F1).
   *
   * Two kinds are out: `generatedAlways()` (`ddl.identity === 'always'`) and
   * `.generatedAlwaysAs(expr)` (`ddl.generatedAs`). `generatedByDefault()` stays IN, because
   * `generated by default as identity` is insertable.
   *
   * The second was design/13 §5 F3's open edge: a generated EXPRESSION column is refused by
   * COPY *by name* (`42P10`, "Generated columns cannot be used in COPY"), so before the DSL
   * could declare one, the default list could not know about it and the refusal arrived from
   * the server. Now it is a `UsageError` from `copyColumns` with the column named — and an
   * explicit `{ columns }` naming it still reaches the server, because `42P10` is COPY's rule
   * and not ours to restate.
   */
  readonly insertableKeys: readonly string[]
  /**
   * The TS keys of columns declared `GENERATED ALWAYS AS (<expr>) STORED`, in declaration order.
   *
   * Apart from `insertableKeys`, and the difference is what COPY needs: an identity column IS
   * writable by COPY (that is what makes a restore possible, design/13 §5's F3 rule), while a
   * generated EXPRESSION column is refused by PostgreSQL outright — `42P10`, *"Generated columns
   * cannot be used in COPY"*. So the two kinds are both out of the default list and only one of
   * them may be named explicitly, which no single set can say.
   *
   * The same frozen empty array for every table that declares none, which is nearly all of them.
   */
  readonly generatedKeys: readonly string[]
  /** TS key → column. `posts.authorId` → the `"author_id"` meta. */
  readonly byKey: Readonly<Record<string, ColumnMeta>>
  /**
   * `05` §6.2's `.$default(fn)` — TS key → factory — or `undefined` when no column declares one.
   *
   * `undefined` rather than an empty record so the write builders can skip the whole feature with
   * one property read: this is on the path of every insert, including the 1 000-row batch design/12
   * §4 P item 2 spent a workstream on, and a schema that uses no `$default` must pay nothing.
   */
  readonly clientDefaults: Readonly<Record<string, () => unknown>> | undefined
  /** `.$onUpdate(fn)`, same shape and the same `undefined`-when-empty rule. */
  readonly clientOnUpdates: Readonly<Record<string, () => unknown>> | undefined
}

const CACHE = new WeakMap<
  CodecRegistry,
  { gen: number; tables: WeakMap<TableLike, TableCodecMeta> }
>()

/**
 * Schema table → compiler metadata, memoised per (registry, table).
 *
 * Idempotent: two calls with the same registry return the *same object*, so a builder can call it
 * per query method without allocating. The memo is dropped wholesale when the registry's
 * generation moves, which is the only way a column's codec can change.
 */
export function metaOf(t: TableLike, registry: CodecRegistry = defaultRegistry()): TableCodecMeta {
  let entry = CACHE.get(registry)
  if (entry === undefined || entry.gen !== registry.generation) {
    entry = { gen: registry.generation, tables: new WeakMap() }
    CACHE.set(registry, entry)
  }
  const hit = entry.tables.get(t)
  if (hit !== undefined) return hit
  const built = build(t, registry)
  entry.tables.set(t, built)
  return built
}

/** Shared, so a schema with no generated column allocates nothing for the fact that it has none. */
const NO_GENERATED: readonly string[] = Object.freeze([])

function build(t: TableLike, registry: CodecRegistry): TableCodecMeta {
  const rt = t.$
  const table = tableMeta(rt.schema ?? 'public', rt.name)

  const columns: ColumnMeta[] = []
  const keys: string[] = []
  const insertableKeys: string[] = []
  let generatedKeys: string[] | undefined
  const byKey: Record<string, ColumnMeta> = {}
  let clientDefaults: Record<string, () => unknown> | undefined
  let clientOnUpdates: Record<string, () => unknown> | undefined

  for (const ref of rt.columns) {
    const meta = columnMeta(
      ref.dbName,
      codecFor(ref.column.ddl, registry, rt.name, ref.key, rt.schema ?? 'public'),
    )
    columns.push(meta)
    keys.push(ref.key)
    const cddl = ref.column.ddl
    if (cddl.identity !== 'always' && cddl.generatedAs === undefined) insertableKeys.push(ref.key)
    if (cddl.generatedAs !== undefined) (generatedKeys ??= []).push(ref.key)
    byKey[ref.key] = meta
    // The `$` law (design/05 D4) keeps these out of the DDL and the migration IR; it does not keep
    // them out of the runtime, which is the half that was never wired up.
    const ts = ref.column.ts
    if (ts.defaultFn !== undefined) (clientDefaults ??= {})[ref.key] = ts.defaultFn
    if (ts.onUpdateFn !== undefined) (clientOnUpdates ??= {})[ref.key] = ts.onUpdateFn
  }

  return {
    table,
    columns: Object.freeze(columns),
    keys: Object.freeze(keys),
    insertableKeys: Object.freeze(insertableKeys),
    generatedKeys: generatedKeys === undefined ? NO_GENERATED : Object.freeze(generatedKeys),
    byKey: Object.freeze(byKey),
    clientDefaults: clientDefaults === undefined ? undefined : Object.freeze(clientDefaults),
    clientOnUpdates: clientOnUpdates === undefined ? undefined : Object.freeze(clientOnUpdates),
  }
}

/**
 * Resolve one column's codec.
 *
 * The DSL records the *declared* PG type in `ddl.pgType`, with `[]` appended once per `.array()`
 * call and `arrayDim` counting them. Three cases, in order:
 *
 *  - **enum** — `ddl.enumName` is set. The codec comes from the registry, which only has it after
 *    `resolveDynamic` has read this database's `pg_enum`. Before that we mint a *pending* codec
 *    from the labels the schema declared: it encodes and decodes correctly (an enum is text plus a
 *    membership check) and its `oid` is `undefined`, which is exactly what 02 §4.6 promises —
 *    a user type's OID is not stable across databases and is never baked in.
 *
 *  - **array** — `arrayDim >= 1`. Resolved by stripping every `[]` and wrapping the element codec
 *    ONCE, no matter how many times `.array()` was called. That is not a shortcut: PostgreSQL has
 *    no distinct multi-dimensional array *type*. `text[]` and `text[][]` are both OID 1009 and
 *    dimensionality is a property of the value, which is why `arrayCodec.decodeText` already walks
 *    nested literals. Wrapping twice would invent a type PG does not have.
 *
 *  - **scalar** — `registry.byName(pgType)`.
 */
export function codecFor(
  ddl: ColumnDdl,
  registry: CodecRegistry,
  table: string,
  column: string,
  schema?: string,
): AnyCodec {
  if (ddl.enumName !== undefined) {
    const found = registry.byName(arrayName(ddl.enumName, ddl.arrayDim))
    if (found) return found
    const element = pendingEnumCodec(ddl.enumName, ddl.enumValues ?? [], schema)
    return ddl.arrayDim > 0 ? arrayCodecOf(element, registry) : element
  }

  const base = ddl.pgType.replace(/(\[\])+$/, '')
  const element = registry.byName(base) ?? registry.byName(withoutTypeModifier(base))
  if (element === undefined) {
    throw new NoCodecError(
      table,
      column,
      ddl.pgType,
      `Register one with \`registry.register(codec)\` — see \`definePgType()\` for an extension ` +
        `type — or declare the column with a built-in builder. Names the registry knows are the ` +
        `PostgreSQL type names ('int8', 'timestamptz', 'jsonb', …), the named alternates ` +
        `('int8:number', 'numeric:number', 'timestamptz:string') and the shipped extension types ` +
        `('citext', 'vector').`,
    )
  }
  return ddl.arrayDim > 0 ? arrayCodecOf(element, registry) : element
}

function arrayName(name: string, dim: number): string {
  return dim > 0 ? `${name}[]` : name
}

/**
 * `'vector(1536)'` → `'vector'`, `'varchar(50)'` → `'varchar'`.
 *
 * A **typmod is not a type**. PostgreSQL has one `varchar` (OID 1043) and the length rides in
 * `atttypmod`; pgvector has one `vector` and the dimension rides there too. So a column declared
 * `vector(1536)` decodes through the `vector` codec, and the parenthesised part is DDL — which is
 * why it stays on `ddl.pgType` verbatim (the kit emits that string) and is stripped only here.
 *
 * Tried second, never first: a type whose real name contains parentheses would otherwise lose to
 * a same-prefixed one, and `t.raw('numeric(10,2)')` must reach `numeric` and not `numeric(10`.
 * This is also what makes design/05 §5.3's escape hatch queryable — `t.raw('varchar(50)')` used
 * to declare a column `metaOf` then refused to build a codec for.
 */
function withoutTypeModifier(pgType: string): string {
  return pgType.replace(/\s*\([^()]*\)$/, '')
}

/**
 * An enum codec with no OID, for the window between schema definition and `resolveDynamic`.
 *
 * Deliberately NOT registered: registering it by name would make the real one look like an
 * override at connect time, and registering it by OID is impossible because it has none.
 */
function pendingEnumCodec(name: string, labels: readonly string[], schema?: string): AnyCodec {
  const set = new Set(labels)
  const check = (v: unknown): string => {
    if (typeof v !== 'string' || (set.size > 0 && !set.has(v))) {
      throw new TypeError(
        `pg-prime: '${String(v)}' is not a member of enum ${name} [${labels.join(', ')}]`,
      )
    }
    return v
  }
  return {
    name,
    oid: undefined,
    paramOid: undefined,
    // Quoted and qualified exactly as `registry.sqlNameOf` does after `resolveDynamic`, so the
    // `::type` cast a statement emits is byte-identical before and after the registry has met the
    // database. The bare spelling was two bugs at once: `::user_role` differs from
    // `::"public"."user_role"` — so a golden taken before connect did not match one taken after —
    // and an unqualified name 42704s whenever the type's schema is off `search_path`.
    sqlName:
      schema === undefined
        ? quoteIdentPart(name)
        : `${quoteIdentPart(schema)}.${quoteIdentPart(name)}`,
    typeClass: 'enum',
    jsonEncode: 'native',
    encode: (v) => check(v),
    decodeText: (raw) => check(raw),
    decodeJson: (raw) => check(raw),
  }
}
