// Generate `src/versions.ts` — the dependency ranges the scaffold writes into a new project.
//
//   node scripts/versions.mjs [--check]
//
// design/13 §3 X: the file is GENERATED at build time from the workspace's own `package.json`s and
// is never committed (`.gitignore`). The reason is design/13 decision 6: `@pg-prime/create` is in
// the fixed version group with `pg-prime` and `@pg-prime/kit` precisely so that a scaffolder pins
// what it scaffolds, and a pin is exact only if it is read from the versions being released rather
// than typed by hand into a file that then rots.
//
// `build` and `typecheck` both run it first, and so does the vitest global setup, because a
// checkout has no `src/versions.ts` until something does.
import { existsSync, readFileSync, writeFileSync } from 'node:fs'
import { dirname, join } from 'node:path'
import { fileURLToPath } from 'node:url'

const HERE = dirname(fileURLToPath(import.meta.url))
const PKG_DIR = join(HERE, '..')
const ROOT = join(PKG_DIR, '..', '..')
const OUT = join(PKG_DIR, 'src', 'versions.ts')

const read = (path) => JSON.parse(readFileSync(path, 'utf8'))
const pkg = (rel) => read(join(ROOT, rel, 'package.json'))

/** `^1.2.3` from a workspace package's own version. */
const caret = (version) => `^${version}`

const root = read(join(ROOT, 'package.json'))
const kit = pkg('packages/pg-prime-kit')

/**
 * `@pg-prime/testing` is versioned INDEPENDENTLY of this package (design/13 decision 6), so its
 * range is read from its own manifest rather than assumed to be ours. Its content is another
 * workstream's (§3 T); only the version is read here, and the placeholder manifest has been in the
 * repository since the names were reserved.
 */
const testingVersion = pkg('packages/pg-prime-testing').version

/** `"typescript59": "npm:typescript@5.9.3"` — the consumer floor (design/08 §2.2), not tsgo. */
const typescriptFloor = /@(\d+\.\d+\.\d+)$/.exec(root.devDependencies['typescript59'])?.[1]
if (!typescriptFloor) {
  throw new Error('versions: root devDependencies.typescript59 is not `npm:typescript@x.y.z`')
}

const entries = {
  pgPrime: caret(pkg('packages/pg-prime').version),
  kit: caret(kit.version),
  testing: caret(testingVersion),
  pg: kit.dependencies['pg'],
  typescript: `^${typescriptFloor}`,
  typesNode: root.devDependencies['@types/node'],
  vitest: root.devDependencies['vitest'],
  pglite: root.devDependencies['@electric-sql/pglite'],
}

for (const [key, value] of Object.entries(entries)) {
  if (typeof value !== 'string' || value.length === 0) {
    throw new Error(`versions: could not resolve a range for ${key}`)
  }
}

const text = [
  '// GENERATED by scripts/versions.mjs — do not edit, and do not commit it (.gitignore).',
  '//',
  '// The dependency ranges a scaffolded project is written with, read from the workspace at build',
  '// time so that a release pins exactly the versions it ships beside (design/13 decision 6).',
  "import type { Versions } from './types.js'",
  '',
  'export const VERSIONS: Versions = {',
  ...Object.entries(entries).map(([k, v]) => `  ${k}: '${v}',`),
  '}',
  '',
].join('\n')

if (process.argv.includes('--check')) {
  const onDisk = existsSync(OUT) ? readFileSync(OUT, 'utf8') : null
  if (onDisk !== text) {
    console.error(`versions: ${OUT} is missing or stale — run \`node scripts/versions.mjs\``)
    process.exit(1)
  }
  console.log('versions: up to date')
} else if (!existsSync(OUT) || readFileSync(OUT, 'utf8') !== text) {
  writeFileSync(OUT, text)
}
