-- Evolution fixture — the CURRENT state.
--
-- The acceptance fixture proves CREATE-from-empty. This one proves the ALTER
-- paths, which is where a differ actually earns its keep: column type widening,
-- DROP DEFAULT, SET NOT NULL, ADD/DROP COLUMN, ADD UNIQUE, ADD FOREIGN KEY,
-- a NOT VALID CHECK (convalidated), index churn, ALTER SEQUENCE, and a column
-- rename that is only a rename because an annotation says so.

CREATE TYPE public.order_status AS ENUM ('pending', 'paid');

CREATE TABLE public.customers (
  id            bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  email         text NOT NULL,
  legacy_code   varchar(8),
  nickname      text,
  signup_source text DEFAULT 'web'
);

CREATE TABLE public.orders (
  id          bigint              GENERATED ALWAYS AS IDENTITY PRIMARY KEY,
  customer_id bigint              NOT NULL,
  status      public.order_status NOT NULL DEFAULT 'pending',
  note        text
);

CREATE INDEX orders_note_idx ON public.orders (note);

CREATE SEQUENCE public.ticket_seq AS integer START WITH 1 INCREMENT BY 1;
