-- Evolution fixture — the DESIRED state.
--
-- vs current:
--   customers.legacy_code   varchar(8) -> varchar(16)     (ALTER COLUMN … TYPE)
--   customers.nickname      -> full_name                   (rename, hint-driven)
--   customers.signup_source DEFAULT 'web' -> none, NOT NULL(DROP DEFAULT, SET NOT NULL)
--   customers.country       added with a constant default  (ADD COLUMN, no rewrite)
--   customers_email_key     added                          (ADD UNIQUE)
--   orders.note             dropped                        (DROP COLUMN + its index)
--   orders.total            added
--   orders_customer_fkey    added                          (ADD FK, NOT VALID + VALIDATE)
--   orders_total_ck         added NOT VALID                (convalidated = false)
--   orders_customer_idx     added
--   ticket_seq              integer/1 -> bigint/5          (ALTER SEQUENCE)

CREATE TYPE public.order_status AS ENUM ('pending', 'paid');

CREATE TABLE public.customers (
  id            bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  email         text NOT NULL,
  legacy_code   varchar(16),
  full_name     text,
  signup_source text NOT NULL,
  country       text NOT NULL DEFAULT 'US',
  CONSTRAINT customers_email_key UNIQUE (email)
);

CREATE TABLE public.orders (
  id          bigint              GENERATED ALWAYS AS IDENTITY PRIMARY KEY,
  customer_id bigint              NOT NULL REFERENCES public.customers (id),
  status      public.order_status NOT NULL DEFAULT 'pending',
  total       numeric(10,2)       NOT NULL DEFAULT 0
);

-- an intentionally unvalidated constraint: validation state is an orthogonal
-- axis in the IR, so this must survive a round trip as `validated: false`
ALTER TABLE public.orders ADD CONSTRAINT orders_total_ck CHECK (total >= 0) NOT VALID;

CREATE INDEX orders_customer_idx ON public.orders (customer_id);

CREATE SEQUENCE public.ticket_seq AS bigint START WITH 1 INCREMENT BY 5;
