-- Acceptance fixture: 3 tables, FKs, an enum, a partial index, identity columns,
-- a standalone sequence, CHECK + UNIQUE constraints.
-- Declared → diff vs empty DB → apply → re-extract → the diff must be EMPTY.

CREATE TYPE public.order_status AS ENUM ('pending', 'paid', 'shipped');

CREATE TABLE public.users (
  id            bigint      GENERATED ALWAYS AS IDENTITY PRIMARY KEY,
  email         text        NOT NULL,
  display_name  text,
  created_at    timestamptz NOT NULL DEFAULT now(),
  CONSTRAINT users_email_key UNIQUE (email),
  CONSTRAINT users_email_lower_ck CHECK (email = lower(email))
);

CREATE TABLE public.orders (
  id        bigint              GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  user_id   bigint              NOT NULL REFERENCES public.users (id) ON DELETE CASCADE,
  status    public.order_status NOT NULL DEFAULT 'pending',
  total     numeric(12,2)       NOT NULL DEFAULT 0,
  placed_at timestamptz         NOT NULL DEFAULT now()
);

CREATE TABLE public.order_items (
  order_id bigint  NOT NULL REFERENCES public.orders (id) ON DELETE CASCADE,
  line_no  integer NOT NULL,
  sku      text    NOT NULL,
  qty      integer NOT NULL DEFAULT 1,
  PRIMARY KEY (order_id, line_no),
  CONSTRAINT order_items_qty_ck CHECK (qty > 0)
);

-- partial index whose predicate evaluates an enum label
CREATE INDEX orders_open_idx ON public.orders (user_id, placed_at DESC) WHERE status <> 'shipped';
CREATE INDEX order_items_sku_idx ON public.order_items (sku);

CREATE SEQUENCE public.invoice_no_seq AS bigint START WITH 1000 INCREMENT BY 1;
