// GENERATED by tools/api-snapshot.mjs — do not edit by hand.
//
// The `types@<5.9` gate of design/08 §2.2, first in every condition object of every subpath in
// package.json. A consumer on TypeScript < 5.9 resolves `pg-prime` to THIS file instead of the
// real declarations, so every name still exists and every USE of one lands the message in the
// error text. Verified against TypeScript 5.8.3 by tools/pack-smoke.mjs on every run:
//
//   consumer.ts(12,15): error TS2349: This expression is not callable.
//     Type '{ ERROR: "pg-prime requires TypeScript >= 5.9 — see https://pg-prime.dev/ts"; }' has no call signatures.
//
// Naming the key `ERROR` rather than a `__dunder__` is §2.2's own refinement over Kysely's
// version: it reads first in a truncated hover.
//
// ## `Unsupported<M = …> = M` is an identity alias ON PURPOSE — do not "simplify" it
//
// Written the obvious way, `type Unsupported = { ERROR: '…' }`, TypeScript prints the ALIAS NAME
// in the diagnostic — "Type 'Unsupported' has no call signatures" — and the message never
// reaches the user, which defeats the entire file. A generic alias whose body is just its own
// parameter has no alias symbol to print, so the checker falls back to the structural form and
// the sentence appears. Measured, both shapes, on 5.9.3 and 5.8.3.
//
// The lists are the root entry's value and type exports, taken from tools/api-snapshot/*.json.
// `node tools/api-snapshot.mjs --check` fails if this file and that golden disagree, which is
// what stops the stub from silently rotting into "this package has no exported member 'x'".
// The type parameters are optional and are only as many as the real declaration has, so that a
// generic use resolves to the brand instead of erroring with "is not generic".

type Unsupported<Message = { ERROR: 'pg-prime requires TypeScript >= 5.9 — see https://pg-prime.dev/ts' }> = Message

export declare const ALTERNATE_CODECS: Unsupported
export declare const AbortError: Unsupported
export declare const AccessError: Unsupported
export declare const AuthenticationError: Unsupported
export declare const BuilderError: Unsupported
export declare const COLS: Unsupported
export declare const CachedPlanChangedError: Unsupported
export declare const CheckViolationError: Unsupported
export declare const CodecMismatchError: Unsupported
export declare const ConfigError: Unsupported
export declare const ConnectionError: Unsupported
export declare const ConnectionRefusedError: Unsupported
export declare const ConnectionTerminatedError: Unsupported
export declare const ConnectionTimeoutError: Unsupported
export declare const DATE_BRAND: Unsupported
export declare const DataError: Unsupported
export declare const DbClosedError: Unsupported
export declare const DeadlockDetectedError: Unsupported
export declare const DecodePlanError: Unsupported
export declare const DiskFullError: Unsupported
export declare const DivisionByZeroError: Unsupported
export declare const DuplicateStatementError: Unsupported
export declare const DuplicateTableError: Unsupported
export declare const ERR: Unsupported
export declare const ExclusionViolationError: Unsupported
export declare const ForeignKeyViolationError: Unsupported
export declare const HandleMisuseError: Unsupported
export declare const INS: Unsupported
export declare const IdleInTransactionTimeoutError: Unsupported
export declare const InFailedTransactionError: Unsupported
export declare const IndeterminateCommitError: Unsupported
export declare const InsufficientPrivilegeError: Unsupported
export declare const InsufficientResourcesError: Unsupported
export declare const IntegrityConstraintError: Unsupported
export declare const InvalidDatetimeFormatError: Unsupported
export declare const InvalidFragmentError: Unsupported
export declare const InvalidIdentifierError: Unsupported
export declare const InvalidPasswordError: Unsupported
export declare const InvalidStatementNameError: Unsupported
export declare const InvalidTextRepresentationError: Unsupported
export declare const LockNotAvailableError: Unsupported
export declare const MAX_IDENT_BYTES: Unsupported
export declare const MAX_NOTIFY_PAYLOAD_BYTES: Unsupported
export declare const META: Unsupported
export declare const NAME: Unsupported
export declare const NoCodecError: Unsupported
export declare const NotNullViolationError: Unsupported
export declare const NullOperandError: Unsupported
export declare const NumericValueOutOfRangeError: Unsupported
export declare const OUT: Unsupported
export declare const OperatorInterventionError: Unsupported
export declare const OutOfMemoryError: Unsupported
export declare const POOLER_MODES: Unsupported
export declare const POOLER_PROFILES: Unsupported
export declare const PgDecodeError: Unsupported
export declare const PgDriverError: Unsupported
export declare const PgEncodeError: Unsupported
export declare const PgPrimeError: Unsupported
export declare const PoolTimeoutError: Unsupported
export declare const PreparedStatementError: Unsupported
export declare const QueryCanceledError: Unsupported
export declare const QueryError: Unsupported
export declare const QueryTimeoutError: Unsupported
export declare const REFS: Unsupported
export declare const RELS: Unsupported
export declare const ReadOnlySqlTransactionError: Unsupported
export declare const Registry: Unsupported
export declare const RestrictViolationError: Unsupported
export declare const SCHEMA: Unsupported
export declare const SEL: Unsupported
export declare const SELECT_SOURCE: Unsupported
export declare const SEMCONV: Unsupported
export declare const SQLSTATE_CLASS_FALLBACK: Unsupported
export declare const SQLSTATE_MAP: Unsupported
export declare const SRC: Unsupported
export declare const SchemaError: Unsupported
export declare const SchemaObjectError: Unsupported
export declare const SerializationFailureError: Unsupported
export declare const SqlSyntaxError: Unsupported
export declare const StringDataRightTruncationError: Unsupported
export declare const TABLES: Unsupported
export declare const TimeoutError: Unsupported
export declare const TlsError: Unsupported
export declare const TooManyConnectionsError: Unsupported
export declare const TooManyParametersError: Unsupported
export declare const TransactionAbandonedError: Unsupported
export declare const TransactionClosedError: Unsupported
export declare const TransactionError: Unsupported
export declare const TransactionRollback: Unsupported
export declare const TransactionTimeoutError: Unsupported
export declare const UPD: Unsupported
export declare const UndefinedColumnError: Unsupported
export declare const UndefinedFunctionError: Unsupported
export declare const UndefinedTableError: Unsupported
export declare const UniqueViolationError: Unsupported
export declare const UnknownQueryError: Unsupported
export declare const UnsafeLiteralError: Unsupported
export declare const UnsupportedInPoolerModeError: Unsupported
export declare const UnsupportedNodeError: Unsupported
export declare const UsageError: Unsupported
export declare const abs: Unsupported
export declare const add: Unsupported
export declare const adjacent: Unsupported
export declare const allOf: Unsupported
export declare const and: Unsupported
export declare const anyOf: Unsupported
export declare const arrayCodec: Unsupported
export declare const arrayCodecOf: Unsupported
export declare const arrayConcat: Unsupported
export declare const arrayContainedBy: Unsupported
export declare const arrayContains: Unsupported
export declare const arrayLength: Unsupported
export declare const asExpr: Unsupported
export declare const asc: Unsupported
export declare const between: Unsupported
export declare const bigint: Unsupported
export declare const bitCodec: Unsupported
export declare const boolCodec: Unsupported
export declare const boolean: Unsupported
export declare const bpcharCodec: Unsupported
export declare const builtinCodecs: Unsupported
export declare const byteaCodec: Unsupported
export declare const cast: Unsupported
export declare const charCodec: Unsupported
export declare const check: Unsupported
export declare const cidrCodec: Unsupported
export declare const classForSqlState: Unsupported
export declare const clearDescribeCache: Unsupported
export declare const clusterOn: Unsupported
export declare const coalesce: Unsupported
export declare const comment: Unsupported
export declare const compileOnly: Unsupported
export declare const concat: Unsupported
export declare const containedByNet: Unsupported
export declare const containsNet: Unsupported
export declare const createRegistry: Unsupported
export declare const date: Unsupported
export declare const dateCodec: Unsupported
export declare const daterangeCodec: Unsupported
export declare const defaultRegistry: Unsupported
export declare const defineRelations: Unsupported
export declare const defineSchema: Unsupported
export declare const desc: Unsupported
export declare const describeCacheStats: Unsupported
export declare const div: Unsupported
export declare const enumCodec: Unsupported
export declare const enumColumn: Unsupported
export declare const eq: Unsupported
export declare const exclude: Unsupported
export declare const exists: Unsupported
export declare const float4Codec: Unsupported
export declare const float8Codec: Unsupported
export declare const fn: Unsupported
export declare const foreignKey: Unsupported
export declare const fragmentDdlText: Unsupported
export declare const gt: Unsupported
export declare const gte: Unsupported
export declare const has: Unsupported
export declare const hasAll: Unsupported
export declare const hasAllKeys: Unsupported
export declare const hasAnyKey: Unsupported
export declare const hasKey: Unsupported
export declare const hasLoneSurrogate: Unsupported
export declare const hasNul: Unsupported
export declare const ilike: Unsupported
export declare const inList: Unsupported
export declare const inQuery: Unsupported
export declare const index: Unsupported
export declare const inetCodec: Unsupported
export declare const int2Codec: Unsupported
export declare const int4Codec: Unsupported
export declare const int4rangeCodec: Unsupported
export declare const int8Codec: Unsupported
export declare const int8NumberCodec: Unsupported
export declare const int8StringCodec: Unsupported
export declare const int8rangeCodec: Unsupported
export declare const integer: Unsupported
export declare const intervalCodec: Unsupported
export declare const iregex: Unsupported
export declare const isCheckViolation: Unsupported
export declare const isDistinctFrom: Unsupported
export declare const isFalse: Unsupported
export declare const isForeignKeyViolation: Unsupported
export declare const isFragment: Unsupported
export declare const isNotDistinctFrom: Unsupported
export declare const isNotFalse: Unsupported
export declare const isNotNull: Unsupported
export declare const isNotNullViolation: Unsupported
export declare const isNotTrue: Unsupported
export declare const isNull: Unsupported
export declare const isServerErrorShape: Unsupported
export declare const isTrue: Unsupported
export declare const isUniqueViolation: Unsupported
export declare const isValidIdentPart: Unsupported
export declare const jsonCodecJson: Unsupported
export declare const jsonConcat: Unsupported
export declare const jsonContainedBy: Unsupported
export declare const jsonContains: Unsupported
export declare const jsonDelete: Unsupported
export declare const jsonDeletePath: Unsupported
export declare const jsonGet: Unsupported
export declare const jsonGetText: Unsupported
export declare const jsonPath: Unsupported
export declare const jsonPathExists: Unsupported
export declare const jsonPathMatch: Unsupported
export declare const jsonPathText: Unsupported
export declare const jsonb: Unsupported
export declare const jsonbCodec: Unsupported
export declare const jsonpathCodec: Unsupported
export declare const kit: Unsupported
export declare const like: Unsupported
export declare const lt: Unsupported
export declare const lte: Unsupported
export declare const macaddr8Codec: Unsupported
export declare const macaddrCodec: Unsupported
export declare const matches: Unsupported
export declare const mod: Unsupported
export declare const moneyCodec: Unsupported
export declare const mul: Unsupported
export declare const nameCodec: Unsupported
export declare const neq: Unsupported
export declare const nest: Unsupported
export declare const nestNullable: Unsupported
export declare const normaliseError: Unsupported
export declare const not: Unsupported
export declare const notExists: Unsupported
export declare const notILike: Unsupported
export declare const notIRegex: Unsupported
export declare const notInList: Unsupported
export declare const notLike: Unsupported
export declare const notRegex: Unsupported
export declare const numeric: Unsupported
export declare const numericCodec: Unsupported
export declare const numericNumberCodec: Unsupported
export declare const numrangeCodec: Unsupported
export declare const oidCodec: Unsupported
export declare const omit: Unsupported
export declare const or: Unsupported
export declare const over: Unsupported
export declare const overlaps: Unsupported
export declare const overlapsNet: Unsupported
export declare const parseArrayLiteral: Unsupported
export declare const partitionBy: Unsupported
export declare const partitionOf: Unsupported
export declare const pgDomain: Unsupported
export declare const pgDriver: Unsupported
export declare const pgEnum: Unsupported
export declare const pgExtension: Unsupported
export declare const pgLsnCodec: Unsupported
export declare const pgPrime: Unsupported
export declare const pgSchema: Unsupported
export declare const pgSequence: Unsupported
export declare const pgTable: Unsupported
export declare const placeholder: Unsupported
export declare const presets: Unsupported
export declare const primaryKey: Unsupported
export declare const profileOf: Unsupported
export declare const quoteIdentPart: Unsupported
export declare const quoteIdentPath: Unsupported
export declare const quoteStringLiteral: Unsupported
export declare const rangeContainedBy: Unsupported
export declare const rangeContains: Unsupported
export declare const rangeIntersection: Unsupported
export declare const rangeLower: Unsupported
export declare const rangeOverlaps: Unsupported
export declare const rangeUnion: Unsupported
export declare const rangeUpper: Unsupported
export declare const raw: Unsupported
export declare const regex: Unsupported
export declare const renamedFrom: Unsupported
export declare const resolveRelations: Unsupported
export declare const similarTo: Unsupported
export declare const smallint: Unsupported
export declare const snakeCase: Unsupported
export declare const spanAttributes: Unsupported
export declare const spanName: Unsupported
export declare const sql: Unsupported
export declare const startsWith: Unsupported
export declare const statementStats: Unsupported
export declare const strictlyLeft: Unsupported
export declare const strictlyRight: Unsupported
export declare const sub: Unsupported
export declare const table: Unsupported
export declare const text: Unsupported
export declare const textCodec: Unsupported
export declare const timeCodec: Unsupported
export declare const timestampCodec: Unsupported
export declare const timestamptz: Unsupported
export declare const timestamptzCodec: Unsupported
export declare const timestamptzStringCodec: Unsupported
export declare const timetzCodec: Unsupported
export declare const toNode: Unsupported
export declare const toOrderItem: Unsupported
export declare const toServerErrorData: Unsupported
export declare const tsRank: Unsupported
export declare const tsRankCd: Unsupported
export declare const tsqueryCodec: Unsupported
export declare const tsrangeCodec: Unsupported
export declare const tstzrangeCodec: Unsupported
export declare const tsvectorCodec: Unsupported
export declare const unique: Unsupported
export declare const uniqueIndex: Unsupported
export declare const unknownCodec: Unsupported
export declare const utf8ByteLength: Unsupported
export declare const uuid: Unsupported
export declare const uuidCodec: Unsupported
export declare const val: Unsupported
export declare const varbitCodec: Unsupported
export declare const varchar: Unsupported
export declare const varcharCodec: Unsupported
export declare const writeArrayLiteral: Unsupported
export declare const xmlCodec: Unsupported

export type AbortError = Unsupported
export type AccessError = Unsupported
export type AccessMode = Unsupported
export type AdvisoryLock = Unsupported
export type AdvisoryLockOptions = Unsupported
export type AllRefs<T0 = any> = Unsupported
export type AnyCodec = Unsupported
export type AnyCol = Unsupported
export type AnyFragment = Unsupported
export type AnyHandle = Unsupported
export type AnyOperand<T0 = any> = Unsupported
export type AnyPgEnum = Unsupported
export type AnyQuery = Unsupported
export type AnyRef = Unsupported
export type AnySchema = Unsupported
export type AnyTable = Unsupported
export type ArrayOperand<T0 = any> = Unsupported
export type AsyncDisposable_ = Unsupported
export type AsyncDisposeKey = Unsupported
export type AuthenticationError = Unsupported
export type BoolOperand = Unsupported
export type Bound = Unsupported
export type BuilderError = Unsupported
export type BulkOpts = Unsupported
export type CachedPlanChangedError = Unsupported
export type CallOptions = Unsupported
export type CheckSpec = Unsupported
export type CheckViolationError = Unsupported
export type ClassOperand<T0 = any, T1 = any> = Unsupported
export type Codec<T0 = any, T1 = any, T2 = any> = Unsupported
export type CodecContext = Unsupported
export type CodecIn<T0 = any> = Unsupported
export type CodecMismatch = Unsupported
export type CodecMismatchError = Unsupported
export type CodecOut<T0 = any> = Unsupported
export type CodecPg<T0 = any> = Unsupported
export type CodecRegistry = Unsupported
export type Col<T0 = any> = Unsupported
export type ColMeta = Unsupported
export type Cols = Unsupported
export type ColsAt<T0 = any, T1 = any> = Unsupported
export type ColsAtH<T0 = any> = Unsupported
export type ColsOf<T0 = any> = Unsupported
export type ColumnDdl = Unsupported
export type ColumnKit = Unsupported
export type ColumnRef = Unsupported
export type ColumnRuntime = Unsupported
export type ColumnTsMeta = Unsupported
export type ConfigError = Unsupported
export type ConflictBuilder<T0 = any> = Unsupported
export type ConnectionError = Unsupported
export type ConnectionParams = Unsupported
export type ConnectionRefusedError = Unsupported
export type ConnectionTerminatedError = Unsupported
export type ConnectionTimeoutError = Unsupported
export type ConstraintKind = Unsupported
export type ConstraintRef = Unsupported
export type CopyFromApi = Unsupported
export type CopyOptions = Unsupported
export type CopyResult = Unsupported
export type CopyToApi = Unsupported
export type CteExecutor<T0 = any> = Unsupported
export type CteHandle<T0 = any, T1 = any> = Unsupported
export type DataError = Unsupported
export type DateString = Unsupported
export type Db<T0 = any> = Unsupported
export type DbClosedError = Unsupported
export type DbConfig<T0 = any> = Unsupported
export type DbDiagnosis = Unsupported
export type DeadlockDetectedError = Unsupported
export type DecodePlanError = Unsupported
export type DecoderMode = Unsupported
export type DefaultSpec = Unsupported
export type Defer<T0 = any> = Unsupported
export type DeleteQuery<T0 = any, T1 = any, T2 = any> = Unsupported
export type DescribeCacheStats = Unsupported
export type DiagnosePoolerOptions = Unsupported
export type DiagnosticSignal = Unsupported
export type DiskFullError = Unsupported
export type DivisionByZeroError = Unsupported
export type DuplicateStatementError = Unsupported
export type DuplicateTableError = Unsupported
export type Duration = Unsupported
export type DynamicTypeRequest = Unsupported
export type ErrorContext = Unsupported
export type ErrorOptions = Unsupported
export type ExcludeItem = Unsupported
export type ExcludePair = Unsupported
export type ExclusionViolationError = Unsupported
export type ExecOptions = Unsupported
export type Executor = Unsupported
export type ExplainNode = Unsupported
export type ExplainOptions = Unsupported
export type ExplainResult = Unsupported
export type Expr<T0 = any, T1 = any> = Unsupported
export type ExprOf<T0 = any> = Unsupported
export type FieldOrigin = Unsupported
export type FkAction = Unsupported
export type Fn = Unsupported
export type ForeignKeyExtraInput = Unsupported
export type ForeignKeyOptions = Unsupported
export type ForeignKeyViolationError = Unsupported
export type Fragment<T0 = any> = Unsupported
export type FrameOpts = Unsupported
export type FromRawOpts<T0 = any> = Unsupported
export type FromValuesOpts = Unsupported
export type GeneratedAlwaysAsOptions = Unsupported
export type GroupedQuery<T0 = any, T1 = any, T2 = any, T3 = any> = Unsupported
export type Grouping = Unsupported
export type Handle<T0 = any, T1 = any> = Unsupported
export type HandleKind = Unsupported
export type HandleMisuseError = Unsupported
export type IdentRejectReason = Unsupported
export type IdleInTransactionTimeoutError = Unsupported
export type InFailedTransactionError = Unsupported
export type IndeterminateCommitError = Unsupported
export type IndexColumn = Unsupported
export type IndexColumnLike = Unsupported
export type IndexExpression = Unsupported
export type IndexItem = Unsupported
export type IndexNulls = Unsupported
export type IndexOptions = Unsupported
export type Infer<T0 = any> = Unsupported
export type InferResult<T0 = any> = Unsupported
export type Insert<T0 = any> = Unsupported
export type InsertPatch<T0 = any> = Unsupported
export type InsertQuery<T0 = any, T1 = any, T2 = any> = Unsupported
export type InsertRow<T0 = any> = Unsupported
export type Insertable<T0 = any> = Unsupported
export type InsufficientPrivilegeError = Unsupported
export type InsufficientResourcesError = Unsupported
export type IntegrityConstraintError = Unsupported
export type InternalEvent = Unsupported
export type InvalidDatetimeFormatError = Unsupported
export type InvalidFragmentError = Unsupported
export type InvalidIdentifierError = Unsupported
export type InvalidPasswordError = Unsupported
export type InvalidStatementNameError = Unsupported
export type InvalidTextRepresentationError = Unsupported
export type IsolationLevel = Unsupported
export type JsonEncode = Unsupported
export type JsonOperand = Unsupported
export type JsonbOperand = Unsupported
export type ListenOptions = Unsupported
export type Loaded<T0 = any, T1 = any, T2 = any> = Unsupported
export type LockNotAvailableError = Unsupported
export type LockOpts<T0 = any> = Unsupported
export type LogLevel = Unsupported
export type LogOptions = Unsupported
export type LogRecord = Unsupported
export type ManyRel<T0 = any, T1 = any> = Unsupported
export type NetOperand = Unsupported
export type NoCodecError = Unsupported
export type NoHandleEscape<T0 = any> = Unsupported
export type NonNullOperand<T0 = any> = Unsupported
export type NotNullViolationError = Unsupported
export type NoticeEvent = Unsupported
export type NotificationHandler = Unsupported
export type NullOperandError = Unsupported
export type NullRef<T0 = any> = Unsupported
export type NullRow<T0 = any> = Unsupported
export type NumOperand<T0 = any, T1 = any> = Unsupported
export type NumPg = Unsupported
export type NumericValueOutOfRangeError = Unsupported
export type OneRel<T0 = any, T1 = any> = Unsupported
export type Operand<T0 = any> = Unsupported
export type OperatorInterventionError = Unsupported
export type Order = Unsupported
export type OrderArg = Unsupported
export type OrderBy = Unsupported
export type OrmTypeError<T0 = any> = Unsupported
export type OutOfMemoryError = Unsupported
export type PartitionOfOptions = Unsupported
export type PgAcquireOptions = Unsupported
export type PgArrayLiteral = Unsupported
export type PgCapabilities = Unsupported
export type PgConnection = Unsupported
export type PgCopyOptions = Unsupported
export type PgCopyResult = Unsupported
export type PgDateString = Unsupported
export type PgDecodeError = Unsupported
export type PgDescribeResult = Unsupported
export type PgDomain = Unsupported
export type PgDomainOptions = Unsupported
export type PgDriver = Unsupported
export type PgDriverConfig = Unsupported
export type PgDriverError = Unsupported
export type PgDriverErrorData = Unsupported
export type PgEncodeError = Unsupported
export type PgEnum<T0 = any, T1 = any> = Unsupported
export type PgEnumOptions<T0 = any> = Unsupported
export type PgErrorKind = Unsupported
export type PgExecMode = Unsupported
export type PgExtension = Unsupported
export type PgExtensionOptions = Unsupported
export type PgField = Unsupported
export type PgInterval = Unsupported
export type PgLikeClient = Unsupported
export type PgLikeDedicatedClient = Unsupported
export type PgLikePool = Unsupported
export type PgLikeQueryConfig = Unsupported
export type PgLikeResult = Unsupported
export type PgNoticeData = Unsupported
export type PgNotification = Unsupported
export type PgParam = Unsupported
export type PgPrimeError = Unsupported
export type PgPrimeErrorCode = Unsupported
export type PgPrimeOptions<T0 = any> = Unsupported
export type PgQuery = Unsupported
export type PgRawValue = Unsupported
export type PgResult = Unsupported
export type PgResultChunk = Unsupported
export type PgSchema = Unsupported
export type PgSchemaOptions = Unsupported
export type PgSequence = Unsupported
export type PgSequenceOptions = Unsupported
export type PgServerErrorData = Unsupported
export type PgTimestampString = Unsupported
export type PkOf<T0 = any> = Unsupported
export type PlaceholderRef = Unsupported
export type PoolEvent = Unsupported
export type PoolOptions = Unsupported
export type PoolStats = Unsupported
export type PoolTimeoutError = Unsupported
export type PoolerDiagnosis = Unsupported
export type PoolerMode = Unsupported
export type PoolerProfile = Unsupported
export type PrepareOptions = Unsupported
export type PreparedQuery<T0 = any, T1 = any> = Unsupported
export type PreparedStatementError = Unsupported
export type PreparedStatementOptions = Unsupported
export type PrimaryKeyInput = Unsupported
export type Project<T0 = any> = Unsupported
export type ProjectPreJoin<T0 = any> = Unsupported
export type Projectable = Unsupported
export type Projection = Unsupported
export type Query<T0 = any, T1 = any, T2 = any> = Unsupported
export type QueryCanceledError = Unsupported
export type QueryEndEvent = Unsupported
export type QueryError = Unsupported
export type QueryErrorCtor = Unsupported
export type QueryErrorEvent = Unsupported
export type QueryHooks = Unsupported
export type QueryOperation = Unsupported
export type QueryStartEvent = Unsupported
export type QueryTimeoutError = Unsupported
export type Queryable<T0 = any> = Unsupported
export type RangeOperand<T0 = any> = Unsupported
export type RangePg = Unsupported
export type RawQuery = Unsupported
export type RawRow = Unsupported
export type RawShape<T0 = any> = Unsupported
export type ReadOnlySqlTransactionError = Unsupported
export type RecursiveOpts = Unsupported
export type Ref<T0 = any, T1 = any, T2 = any> = Unsupported
export type RefLike = Unsupported
export type RefRuntime = Unsupported
export type RefSpec = Unsupported
export type Refs<T0 = any> = Unsupported
export type RefsAt<T0 = any> = Unsupported
export type RefsOf<T0 = any> = Unsupported
export type RefsOfCols<T0 = any, T1 = any> = Unsupported
export type Registry = Unsupported
export type RelAccessor<T0 = any, T1 = any> = Unsupported
export type RelAggs<T0 = any, T1 = any> = Unsupported
export type RelBuilders<T0 = any> = Unsupported
export type RelConfig<T0 = any> = Unsupported
export type RelMeta<T0 = any> = Unsupported
export type RelNode = Unsupported
export type RelOpts = Unsupported
export type RelOut<T0 = any, T1 = any> = Unsupported
export type RelPickers<T0 = any> = Unsupported
export type Rels = Unsupported
export type RelsAt<T0 = any, T1 = any> = Unsupported
export type RelsRecord<T0 = any> = Unsupported
export type ResolvedRelation = Unsupported
export type ResolvedRelations = Unsupported
export type ResolvedThrough = Unsupported
export type RestrictViolationError = Unsupported
export type ResultRefs<T0 = any> = Unsupported
export type RetryEvent = Unsupported
export type RetryPolicy = Unsupported
export type Row<T0 = any> = Unsupported
export type RowOf<T0 = any> = Unsupported
export type RowSource<T0 = any> = Unsupported
export type RunCallOptions = Unsupported
export type RunOptions = Unsupported
export type RunTiming = Unsupported
export type Runnable<T0 = any> = Unsupported
export type SavepointOptions = Unsupported
export type Schema<T0 = any, T1 = any> = Unsupported
export type SchemaError = Unsupported
export type SchemaExecutor<T0 = any> = Unsupported
export type SchemaObjectError = Unsupported
export type ScopeOf<T0 = any, T1 = any> = Unsupported
export type SelAt<T0 = any, T1 = any> = Unsupported
export type SelectAt<T0 = any> = Unsupported
export type SelectRow<T0 = any> = Unsupported
export type SelectSource<T0 = any> = Unsupported
export type Selectable<T0 = any> = Unsupported
export type SerializationFailureError = Unsupported
export type Session<T0 = any> = Unsupported
export type SessionDefaults = Unsupported
export type SetOps<T0 = any, T1 = any> = Unsupported
export type SetPatch<T0 = any> = Unsupported
export type SetQuery<T0 = any, T1 = any> = Unsupported
export type Simplify<T0 = any> = Unsupported
export type Sources = Unsupported
export type SpanAttributes = Unsupported
export type SpanContext = Unsupported
export type SqlSnapshot = Unsupported
export type SqlState = Unsupported
export type SqlSyntaxError = Unsupported
export type SqlTag = Unsupported
export type StatementMode = Unsupported
export type StatementStats = Unsupported
export type StorageParameters = Unsupported
export type StreamCallOptions = Unsupported
export type StreamOptions = Unsupported
export type StringDataRightTruncationError = Unsupported
export type SubQuery<T0 = any, T1 = any, T2 = any> = Unsupported
export type Subscription = Unsupported
export type Table<T0 = any, T1 = any, T2 = any> = Unsupported
export type TableAt<T0 = any> = Unsupported
export type TableExtra = Unsupported
export type TableOf<T0 = any, T1 = any> = Unsupported
export type TableOptions = Unsupported
export type TableRef = Unsupported
export type TableRuntime = Unsupported
export type Tables = Unsupported
export type TextOperand = Unsupported
export type TextPg = Unsupported
export type TimeoutError = Unsupported
export type TlsError = Unsupported
export type TooManyConnectionsError = Unsupported
export type TooManyParametersError = Unsupported
export type TransactionAbandonedError = Unsupported
export type TransactionClosedError = Unsupported
export type TransactionDefaults = Unsupported
export type TransactionError = Unsupported
export type TransactionRollback = Unsupported
export type TransactionTimeoutError = Unsupported
export type TsqueryOperand = Unsupported
export type TsvectorOperand = Unsupported
export type Tx<T0 = any> = Unsupported
export type TxEndEvent = Unsupported
export type TxOptions = Unsupported
export type TxOptionsBase = Unsupported
export type TxStartEvent = Unsupported
export type TypeClass = Unsupported
export type TypedFragment<T0 = any, T1 = any> = Unsupported
export type UndefinedColumnError = Unsupported
export type UndefinedFunctionError = Unsupported
export type UndefinedTableError = Unsupported
export type UniqueSpec = Unsupported
export type UniqueViolationError = Unsupported
export type UnknownQueryError = Unsupported
export type UnsafeLiteralError = Unsupported
export type UnsupportedInPoolerModeError = Unsupported
export type UnsupportedNodeError = Unsupported
export type Update<T0 = any> = Unsupported
export type UpdateQuery<T0 = any, T1 = any, T2 = any> = Unsupported
export type UpdateRow<T0 = any> = Unsupported
export type Updateable<T0 = any> = Unsupported
export type UsageError = Unsupported
export type ValueRefs<T0 = any> = Unsupported
export type WindowFn = Unsupported
export type WindowLiteral = Unsupported
export type WindowSpec = Unsupported
export type WithOpts = Unsupported
