#!/usr/bin/env node
/**
 * Fetch, pin and trim the third-party schema corpus — design/11 §1.10, `01` §11.6 #5.
 *
 *   node tools/corpus-fetch.mjs [name…] [--accept-pin] [--offline]
 *
 * `migrate verify` being green on three real, third-party schemas is the correctness gate
 * for the migration engine, and a gate is only worth something if the thing it is run
 * against is reproducible. So:
 *
 *  - every download is **sha256-pinned** in this file. A source that changed under us
 *    fails loudly instead of silently changing what the gate means;
 *  - the licence file is fetched with the schema, never assumed;
 *  - trimming is **scripted, not manual**, so the committed `schema.sql` can be
 *    regenerated byte-for-byte from the pinned upstream at any time;
 *  - the trimming uses the kit's own SQL lexer (`sql/statements.ts`), because a `;`
 *    inside a `$$…$$` body is not a statement boundary and a regex over `INSERT` would
 *    cut a function in half.
 *
 * What is removed, and why each is not schema:
 *
 *  - `INSERT` / `COPY` / `SELECT setval(...)` / `UPDATE` / `DELETE` / `TRUNCATE` — data;
 *  - `COPY … FROM stdin;` and everything up to the terminating `\.` — data, and it is
 *    not even SQL;
 *  - psql meta-commands (`\connect`, `\copy`, `\i`, `\echo`, …) — not SQL at all;
 *  - `CREATE`/`DROP`/`ALTER DATABASE`, `\c` — the harness owns the database;
 *  - `GRANT`/`REVOKE`/`ALTER … OWNER TO`/`CREATE ROLE` — cluster-scoped, Tier O in
 *    `06` §2.2, and they name roles that do not exist on the test cluster.
 *
 * Output: `fixtures/corpus/<name>/{schema.sql,LICENSE,SOURCE.md}`, all committed.
 */

import { createHash } from "node:crypto";
import { mkdir, readFile, writeFile } from "node:fs/promises";
import { dirname, join, resolve } from "node:path";
import { fileURLToPath } from "node:url";
import { splitStatements } from "../packages/pg-prime-kit/src/sql/statements.ts";

const HERE = dirname(fileURLToPath(import.meta.url));
const ROOT = resolve(HERE, "..");
const OUT = join(ROOT, "fixtures", "corpus");

/**
 * The corpus. `01` §11.6 #5 asks for three; the fourth is here because it was cheap and
 * because it is the only one of the four with a `nvarchar`-flavoured, SQL-Server-derived
 * shape, which exercises a different corner of the type mapping.
 */
const SOURCES = [
  {
    name: "pagila",
    title: "Pagila",
    // Pinned to a TAG, not to `master`, and specifically to the last tag that is
    // PostgreSQL 15-compatible: `pagila-v4.x` uses `GENERATED ALWAYS AS (…) VIRTUAL` and
    // `uuidv7()`, both PostgreSQL 18, and the design's floor is 15. Pinning also makes the
    // gate mean the same thing next month, which is the whole point of a corpus.
    schema: "https://raw.githubusercontent.com/devrimgunduz/pagila/pagila-v3.1.0/pagila-schema.sql",
    licence: "https://raw.githubusercontent.com/devrimgunduz/pagila/pagila-v3.1.0/LICENSE.txt",
    licenceName: "BSD-3-Clause (Sample Database Copyright, see LICENSE)",
    upstream: "https://github.com/devrimgunduz/pagila",
    sha256: "8ce358e4c8014087b85296694a0893887bd7a4190e3ce407f2721b86b98e5707",
    licenceSha256: "516e7dac679ac1eeb62d5614b01c4e7318154e9a147377d6264954215997ff38",
  },
  {
    name: "northwind",
    title: "Northwind (PostgreSQL port)",
    schema: "https://raw.githubusercontent.com/pthom/northwind_psql/cd0ef28d66369fbe177778e604e4be0f153c9e5c/northwind.sql",
    licence: "https://raw.githubusercontent.com/pthom/northwind_psql/cd0ef28d66369fbe177778e604e4be0f153c9e5c/LICENSE",
    licenceName: "MIT",
    upstream: "https://github.com/pthom/northwind_psql",
    sha256: "0ee30c01ba282f7194f38bf7f99cd6be0470b7ee5f67d0f7ca41fb058d735e0c",
    licenceSha256: "113e017bde8b63ce79bcdd00609039dab93bb846a561b8d28c999b6c4bd1906c",
  },
  {
    name: "adventureworks",
    title: "AdventureWorks (PostgreSQL port)",
    schema:
      "https://raw.githubusercontent.com/lorint/AdventureWorks-for-Postgres/b474991f0df1c4bf55ca4735eb0254ca0709eed2/install.sql",
    licence:
      "https://raw.githubusercontent.com/lorint/AdventureWorks-for-Postgres/b474991f0df1c4bf55ca4735eb0254ca0709eed2/LICENSE",
    licenceName: "MIT",
    upstream: "https://github.com/lorint/AdventureWorks-for-Postgres",
    sha256: "27f71c99365aa5f44dba5d3b7ca092a654fcf50e6931c4dbe96ba2a13f8b7e0e",
    licenceSha256: "4eb50d9ccbc26bbdcab24778da282a3fae72f0cd29e773bfc5fa7caae9b0f231",
  },
  {
    name: "chinook",
    title: "Chinook (PostgreSQL)",
    schema:
      "https://raw.githubusercontent.com/lerocha/chinook-database/7f67772503d71ba90f19283c38e93923addb43fa/ChinookDatabase/DataSources/Chinook_PostgreSql.sql",
    licence:
      "https://raw.githubusercontent.com/lerocha/chinook-database/7f67772503d71ba90f19283c38e93923addb43fa/LICENSE.md",
    licenceName: "MIT",
    upstream: "https://github.com/lerocha/chinook-database",
    sha256: "e3fde5c1a5b51a2a91429a702c9ca6e69ba56e6c7f5e112724d70c3d03db695e",
    licenceSha256: "5064d720db431474b0a0b0cef9d2b5e362b6c6f80602b35c6443b07cbc979f77",
  },
];

const sha256 = (text) => createHash("sha256").update(text, "utf8").digest("hex");

/* -------------------------------------------------------------------------- */
/* trimming                                                                    */
/* -------------------------------------------------------------------------- */

/**
 * Remove psql meta-commands and `COPY … FROM stdin` blocks BEFORE lexing.
 *
 * Neither is SQL: `\.` terminates a copy stream and `\connect` is a client instruction.
 * Feeding either to the lexer would leave a dangling literal and swallow the rest of the
 * file — which is exactly the failure a regex-based trimmer produces silently.
 */
function stripNonSql(text) {
  const lines = text.split(/\r?\n/);
  const out = [];
  let inCopy = false;
  for (const line of lines) {
    if (inCopy) {
      if (line.trim() === "\\.") inCopy = false;
      continue;
    }
    if (/^\s*COPY\b[\s\S]*\bFROM\s+stdin\s*;?\s*$/i.test(line)) {
      inCopy = true;
      continue;
    }
    if (/^\s*\\/.test(line)) continue; // \connect, \copy, \i, \echo, \.
    out.push(line);
  }
  return out.join("\n");
}

/** Statements that are data, cluster state or client noise rather than schema. */
const DROP = [
  /^INSERT\s/i,
  /^COPY\s/i,
  /^UPDATE\s/i,
  /^DELETE\s+FROM\b/i,
  /^TRUNCATE\b/i,
  /^SELECT\s+(pg_catalog\.)?setval\s*\(/i,
  /^CREATE\s+DATABASE\b/i,
  /^DROP\s+DATABASE\b/i,
  /^ALTER\s+DATABASE\b/i,
  /^CREATE\s+ROLE\b/i,
  /^DROP\s+ROLE\b/i,
  /^ALTER\s+ROLE\b/i,
  /^GRANT\b/i,
  /^REVOKE\b/i,
  /^ALTER\s+DEFAULT\s+PRIVILEGES\b/i,
  // Any ALTER that assigns an owner. The object name may be quoted, schema-qualified or carry a
  // signature (`ALTER DOMAIN public."bıgınt" …`, `ALTER FUNCTION public.f(text, text) …`), which a
  // `\w+` chain never matches — CI run 33162089194 went red on exactly that, on a cluster whose
  // superuser is not called `postgres`.
  /^ALTER\s[\s\S]*\bOWNER\s+TO\b/i,
  /^ANALYZE\b/i,
  /^VACUUM\b/i,
  /^CHECKPOINT\b/i,
  /^BEGIN$/i,
  /^COMMIT$/i,
  /^START\s+TRANSACTION\b/i,
];

/**
 * A `SET`/`SELECT set_config` that a dump uses to configure ITS OWN session is kept —
 * `search_path` above all, because the objects that follow depend on it — while anything
 * that names a role or a tablespace is dropped, since neither exists on a test cluster.
 */
function keepSet(statement) {
  if (!/^(SET|SELECT\s+(pg_catalog\.)?set_config)\b/i.test(statement)) return null;
  if (/\brole\b/i.test(statement)) return false;
  if (/\bdefault_tablespace\b/i.test(statement) && !/=\s*''/.test(statement)) return false;
  return true;
}

export function trim(text) {
  const statements = splitStatements(stripNonSql(text));
  const kept = [];
  const dropped = new Map();
  for (const statement of statements) {
    const s = statement.trim();
    if (s === "") continue;
    const set = keepSet(s);
    if (set === true) {
      kept.push(s);
      continue;
    }
    if (set === false) {
      dropped.set("SET", (dropped.get("SET") ?? 0) + 1);
      continue;
    }
    const rule = DROP.find((re) => re.test(s));
    if (rule) {
      const verb = /^\w+(\s+\w+)?/.exec(s)?.[0]?.toUpperCase() ?? "?";
      dropped.set(verb, (dropped.get(verb) ?? 0) + 1);
      continue;
    }
    kept.push(s);
  }
  return { kept, dropped };
}

/* -------------------------------------------------------------------------- */

async function fetchText(url) {
  const response = await fetch(url, { redirect: "follow" });
  if (!response.ok) throw new Error(`GET ${url} → ${response.status} ${response.statusText}`);
  return response.text();
}

async function one(source, { acceptPin, offline }) {
  const dir = join(OUT, source.name);
  if (offline) {
    const existing = await readFile(join(dir, "schema.sql"), "utf8");
    return { name: source.name, statements: existing.split(/^-- pg-prime:corpus/m).length, skipped: true };
  }
  const [raw, licence] = await Promise.all([fetchText(source.schema), fetchText(source.licence)]);
  const gotSchema = sha256(raw);
  const gotLicence = sha256(licence);

  for (const [label, want, got] of [
    ["schema", source.sha256, gotSchema],
    ["licence", source.licenceSha256, gotLicence],
  ]) {
    if (want === null) {
      if (!acceptPin) {
        throw new Error(
          `${source.name}: no ${label} sha256 pin recorded. The download hashed to ${got}. ` +
            `Re-run with --accept-pin to record it, then paste it into tools/corpus-fetch.mjs.`,
        );
      }
      console.log(`  ${source.name} ${label} sha256: ${got}   (record this in tools/corpus-fetch.mjs)`);
    } else if (want !== got) {
      throw new Error(
        `${source.name}: the ${label} at ${label === "schema" ? source.schema : source.licence} has CHANGED — ` +
          `pinned ${want}, downloaded ${got}. Review the upstream diff before updating the pin.`,
      );
    }
  }

  const { kept, dropped } = trim(raw);
  const header = [
    `-- pg-prime:corpus ${source.name}`,
    `-- Source: ${source.schema}`,
    `-- sha256(upstream): ${gotSchema}`,
    `-- Licence: ${source.licenceName} — see LICENSE beside this file.`,
    "--",
    "-- TRIMMED to schema-only DDL by tools/corpus-fetch.mjs. Regenerate with:",
    "--   node tools/corpus-fetch.mjs " + source.name,
    `-- Dropped: ${[...dropped].map(([k, v]) => `${v}×${k}`).sort().join(", ") || "nothing"}`,
    "",
  ].join("\n");
  const body = `${kept.map((s) => `${s};`).join("\n\n")}\n`;

  await mkdir(dir, { recursive: true });
  await writeFile(join(dir, "schema.sql"), `${header}${body}`, "utf8");
  await writeFile(join(dir, "LICENSE"), licence, "utf8");
  await writeFile(
    join(dir, "SOURCE.md"),
    [
      `# ${source.title}`,
      "",
      `- Upstream: <${source.upstream}>`,
      `- Schema:   <${source.schema}>`,
      `- Licence:  ${source.licenceName} — <${source.licence}>`,
      `- sha256(schema, upstream):  \`${gotSchema}\``,
      `- sha256(LICENSE, upstream): \`${gotLicence}\``,
      "",
      `Trimmed to schema-only DDL by \`tools/corpus-fetch.mjs\`: ${kept.length} statements kept, ` +
        `${[...dropped.values()].reduce((a, b) => a + b, 0)} dropped ` +
        `(${[...dropped].map(([k, v]) => `${v}× ${k}`).sort().join(", ") || "nothing"}).`,
      "",
      "This file is committed so the corpus is reproducible from a pinned upstream, which is",
      "what makes `01` §11.6 #5 (`verify` green on three real third-party schemas) a gate",
      "rather than an anecdote.",
      "",
    ].join("\n"),
    "utf8",
  );
  return { name: source.name, statements: kept.length, dropped: [...dropped] };
}

const argv = process.argv.slice(2);
const acceptPin = argv.includes("--accept-pin");
const offline = argv.includes("--offline");
const names = argv.filter((a) => !a.startsWith("--"));
const wanted = names.length === 0 ? SOURCES : SOURCES.filter((s) => names.includes(s.name));
if (wanted.length === 0) {
  console.error(`no such corpus schema: ${names.join(", ")}. Known: ${SOURCES.map((s) => s.name).join(", ")}`);
  process.exitCode = 1;
} else {
  for (const source of wanted) {
    const result = await one(source, { acceptPin, offline });
    console.log(`${result.name}: ${result.statements} statements`);
  }
}
