// GENERATED by tools/api-snapshot.mjs — do not edit by hand.
//
// The `types@<5.9` gate of design/08 §2.2, first in every condition object of every subpath in
// package.json. A consumer on TypeScript < 5.9 resolves `@pg-prime/testing` to THIS file instead of the
// real declarations, so every name still exists and every USE of one lands the message in the
// error text. Verified against TypeScript 5.8.3 by tools/pack-smoke.mjs on every run:
//
//   consumer.ts(12,15): error TS2349: This expression is not callable.
//     Type '{ ERROR: "@pg-prime/testing requires TypeScript >= 5.9 — see https://pg-prime.dev/ts"; }' has no call signatures.
//
// Naming the key `ERROR` rather than a `__dunder__` is §2.2's own refinement over Kysely's
// version: it reads first in a truncated hover.
//
// ## `Unsupported<M = …> = M` is an identity alias ON PURPOSE — do not "simplify" it
//
// Written the obvious way, `type Unsupported = { ERROR: '…' }`, TypeScript prints the ALIAS NAME
// in the diagnostic — "Type 'Unsupported' has no call signatures" — and the message never
// reaches the user, which defeats the entire file. A generic alias whose body is just its own
// parameter has no alias symbol to print, so the checker falls back to the structural form and
// the sentence appears. Measured, both shapes, on 5.9.3 and 5.8.3.
//
// The lists are the root entry's value and type exports, taken from tools/api-snapshot/*.json.
// `node tools/api-snapshot.mjs --check` fails if this file and that golden disagree, which is
// what stops the stub from silently rotting into "this package has no exported member 'x'".
// The type parameters are optional and are only as many as the real declaration has, so that a
// generic use resolves to the brand instead of erroring with "is not generic".

type Unsupported<Message = { ERROR: '@pg-prime/testing requires TypeScript >= 5.9 — see https://pg-prime.dev/ts' }> = Message

export declare const DEFAULT_SERVER_PARAMETERS: Unsupported
export declare const SCRATCH_PREFIX: Unsupported
export declare const TEST_URL_ENV: Unsupported
export declare const createMockPool: Unsupported
export declare const databaseUrl: Unsupported
export declare const dockerAvailable: Unsupported
export declare const dropScratchDatabase: Unsupported
export declare const expectSql: Unsupported
export declare const isScratchDatabase: Unsupported
export declare const normaliseSql: Unsupported
export declare const onRealPostgres: Unsupported
export declare const probe: Unsupported
export declare const requiresConcurrency: Unsupported
export declare const requiresRealPostgres: Unsupported
export declare const scratchDatabase: Unsupported
export declare const scratchDatabaseName: Unsupported
export declare const serve: Unsupported
export declare const startPglite: Unsupported
export declare const startPostgres: Unsupported

export type CompilableLike = Unsupported
export type CompiledLike = Unsupported
export type MockError = Unsupported
export type MockField = Unsupported
export type MockPool = Unsupported
export type MockPoolOptions = Unsupported
export type MockQueryMode = Unsupported
export type MockResult = Unsupported
export type MockStep = Unsupported
export type PgliteBridge = Unsupported
export type PgliteLike = Unsupported
export type PgliteServer = Unsupported
export type PostgresServer = Unsupported
export type RecordedQuery = Unsupported
export type ScratchDatabase = Unsupported
export type SqlExpectation = Unsupported
export type StartPostgresOptions = Unsupported
export type TestDecl = Unsupported
export type TestServer = Unsupported
